import {
    IconActivity,
    IconAlertTriangle,
    IconArchive,
    IconArrowsExchange,
    IconArrowsSplit,
    IconBell,
    IconBolt,
    IconBookmark,
    IconBox,
    IconBuilding,
    IconBuildingBridge2,
    IconBuildingWarehouse,
    IconClipboardCheck,
    IconClipboardText,
    IconFileSpreadsheet,
    IconFolder,
    IconForms,
    IconHome,
    IconKey,
    IconList,
    IconListCheck,
    IconLogin,
    IconMapPin,
    IconMoon,
    IconPower,
    IconRoad,
    IconSettingsAutomation,
    IconStack2,
    IconTool,
    IconTruck,
    IconUserCog,
    IconUsers,
    IconUsersGroup,
} from '@tabler/icons-react'

/** El icono de cada entrada del menu, por su nombre en routeTable.js. */
export const MENU_ICONS = Object.freeze({
    home: IconHome,
    infrastructure: IconBuildingBridge2,
    packages: IconFolder,
    stations: IconBuilding,
    tracks: IconRoad,
    profiles: IconMapPin,
    disconnectors: IconPower,
    insulators: IconArrowsSplit,
    jobs: IconSettingsAutomation,
    users: IconUsers,
    userProfiles: IconUsersGroup,
    roles: IconKey,
    warehouse: IconBuildingWarehouse,
    materials: IconBox,
    warehouses: IconArchive,
    suppliers: IconTruck,
    projects: IconClipboardText,
    movements: IconArrowsExchange,
    reservations: IconBookmark,
    assemblies: IconStack2,
    maintenance: IconTool,
    assets: IconBolt,
    shifts: IconMoon,
    inspections: IconClipboardCheck,
    defects: IconAlertTriangle,
    reports: IconFileSpreadsheet,
    teams: IconUserCog,
    taskTypes: IconListCheck,
    templates: IconForms,
    notifications: IconBell,
    activity: IconActivity,
    access: IconLogin,
    catalogues: IconList,
})
